### ISSUE TITLE
compile error with packaged rviz_visual_tools

### ISSUE THREAD

**Issue by dylanvaughn** [davetcoleman/clam#13]
Hello!  When compiling the clam arm packages as described here:

http://correll.cs.colorado.edu/clam/?page_id=272

I am getting a compile error:

https://gist.github.com/dylanvaughn/a3e1f3496dc4233e2683

I was able to fix this by using the latest rviz_visual_tools from github instead of the packaged one.

Maybe rviz_visual_tools should be included in the list of packages to get from source in the instructions?

Thanks, Dylan

**Comment by codymtaylor** [comment]
Dylan,
Thanks for that insight.  I'm also getting a compile error, it seems similar to yours - a bunch of trouble with rviz_visual_tools.

My error: 
https://gist.github.com/codymtaylor/93e58fb1a1928924d4c0

I tried downloading rviz_visual_tools from github, reran rosdep and ran catkin_make but that didn't seem to do the trick. How did you make it work?

Thanks,
Cody

**Comment by dylanvaughn** [comment]
Hi Cody - yes, I think I have gotten that error as well.  I had to use a specific commit of the moveit_visual_tools package:

davetcoleman/moveit_visual_tools@f6023d8312798c4eb9718875bb024a7bd348f688

I think a later commit in the moveit_visual_tools package introduced this.

**Comment by davetcoleman** [comment]
Hi guys, I am sorry for these regressions. Trying to keep everything compatible is a difficult process. @dylanvaughn would you be interested in sharing maintainer status of this package? I would give you commit access.

**Comment by dylanvaughn** [comment]
Hi @davetcoleman - yes I would be interested in helping to maintain this - we actually just finished the build of our ClamArm and I expect I will be getting much more familiar with it over the next few months :smile:

**Comment by davetcoleman** [comment]
I just made you a collaborator, and added a note https://github.com/davetcoleman/clam/commit/c0fb78740122cdc6ee91d9b99fb73b0746df80d7

I'm happy to discuss other arrangements as well

**Comment by Allen5102** [comment]
Hi Dylan,

I am actually trying to use the clam arm and I am currently on ubuntu 12.04 using Hydro ... I noticed that both you and Cody had errors while compiling similar to mine ... I don't think there is a rviz_visual_tools for hydro available ... I presume both of you guys are using indigo ... you mentioned using a speciifc commit of moveit_visual_tools ... how exactly do you implement this? Did you copy the CMakeLists.txt file in your link and replace it in the moveit_visual_tools on your computer and then try to compile it? 

Sorry for the newbie questions and any help is appreciated.

Thanks!

**Comment by dylanvaughn** [comment]
Hi @Allen5102 - I haven't used it with hydro am unsure about that.  I did however just push a commit (c98b6f30a73efad2b77f48a1fb88533588cafdb4) to the indigo-devel branch which fixes initial compilation errors for me on indigo.  I also think there has been a more recent version of rviz_visual_tools which has been pushed out to the deb repo so it isn't required to download from github anymore as well. I'll close this issue - feel free to open a new issue if you are still having trouble.

**Comment by Allen5102** [comment]
I will try this thanks a lot for replying!
