### ISSUE TITLE
Servo kit no longer available

### ISSUE THREAD

**Issue by dylanvaughn** [davetcoleman/clam#17]
The servo and bracket kit referenced in the build documentation:

http://correll.cs.colorado.edu/clam/?page_id=110

http://www.roadnarrows.com/store/clam-arm-servo-kit.html

does not seem to work on the road narrows website anymore.

@davetcoleman , I know that you didn't do the hardware but is there a way to list the items that used to be in that kit so we know what we need to build this arm?

**Comment by davetcoleman** [comment]
I've updated the documentation on the build page with a pdf and a list of servos
http://correll.cs.colorado.edu/clam/?page_id=110
